export const EMPTY_FIELD = "Can't be empty"
export const INVALID_EMAIL = "Invalid email"
export const PASSWORD_LENGTH_INCORRECT = "Please check again"
export const PASSWORDS_NOT_EQUAL = "Password not equal"
export const URL_INCORRECT = "Please check the URL"